server:
  port: ":8081"
  content_dir: "./contents/"
  resset: ""

site:
  name: "OAEOE NAV"
  keywords: "nav, site nav"
  description: "site nav"
  logo_path: ""
  favicon: ""
  image:
    banner: aaaa
    banner1: bbb

template:
  dir: "tpl"
  default: "index.html"
  static_dir: "tpl/assets"
