server:
  port: "0.0.0.0:8081"
  content_dir: "./contents/"
  resset: ""

site:
  name: "OAEOE"
  keywords: "导航网站, 导航网址, 网址导航, 网站导航"
  description: "智能网址导航，发现互联网之美，这是你进入各大网站的门户。"
  summary: "智能网址导航 · 发现互联网之美"
  logo_path: ""
  favicon: ""
  copyright: "探索精彩网站"

template:
  dir: "tpl"
  default: "index.html"
  static_dir: "tpl/assets"
